#!/bin/bash

set -e; set -u

TMP="/tmp"

function MAKE_QUICK {
    if [ $1.tex -nt $1.pdf ]; then
        cat slides-head.tex > $TMP/$1.tex
        cat $1.tex >> $TMP/$1.tex
        cat slides-tail.tex >> $TMP/$1.tex
        pdflatex    -output-directory $TMP $TMP/$1
#        biber       --output_directory $TMP $TMP/$1
        pdflatex    -output-directory $TMP $TMP/$1
        cp $TMP/$1.pdf .
    fi
}



cat slides-head.tex > $TMP/index.tex

echo '
{\setbeamertemplate{footline}{}\begin{frame}\titlepage\end{frame}}
\addtocounter{framenumber}{-1}
\begin{frame}[allowframebreaks]{Topics}\tableofcontents{}\end{frame}
' >> $TMP/index.tex

for f in *.tex; do
    if [ $f != "index.tex" -a $f != "slides-head.tex" -a $f != "slides-tail.tex" ] ; then
        if [ -o all ] ; then 
            echo "MAKE_ALL ${f#.tex}"
        else
            MAKE_QUICK ${f%.tex}
        fi
        cat $f >> $TMP/index.tex
    fi
done

cat slides-tail.tex >> $TMP/index.tex

if [[ $@ == **index** ]] ; then
    pdflatex --output-directory $TMP $TMP/index
    cp $TMP/index.pdf .
fi







